name: CI/CD Pipeline
on: pull_request

jobs:
    deploy_app:
        runs-on: ubuntu-latest
        steps:
           - name: greetings
             run: echo "Hello World"
             uses: action/checkout@v2
             run: echo "checkout successful."

