name: CI/CD Pipeline
on: push

jobs:
    deploy_app:
        runs-on: ubuntu-latest
        steps:
           - name: greetings
             run: echo "Hello World"

    deploy_app2:
        runs-on: ubuntu-latest
        steps:
          - name: second-greetings
            run: echo "second greeting"
          - name: show-current-path
            run: pwd |
                 echo "third command has been successful!"
            
