# This is the name of the GitHub Actions workflow
name: CI/CD Pipeline

# The workflow is triggered by a push event on the main branch
on:
  push:
    branches:
      - main

# Define the jobs that will run as part of the workflow
jobs:
  # The build job
  build:
    # Specify the environment for the job to run in
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Step 3: Install project dependencies using npm
      - name: Install dependencies
        run: npm install
        working-directory: ./

      # Step 4: Run tests using npm
      - name: Run tests
        run: npm test
        working-directory: ./

      # Step 5: Build project
      - name: Build project
        run: npm run build
        working-directory: ./

  # The deploy job, which runs after the build job
  deploy:
    # Specify the environment for the job to run in
    runs-on: ubuntu-latest

    # Indicate that this job depends on the build job
    needs: build

    steps:
      # Step 1: Check out the repository's code (again, fresh checkout)
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Deploy the application to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
